spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: markskylarkxx@gmail.com
    password: hvxfrnolwqzwgrmn
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true


  jmx:
    enabled: false
  data:
    redis:
      port: 6379
      host: localhost





server:
  port: 2500



config: classpath:logback.xml
logging:
  file:
    name: logs/myapp.log
admin:
  name: Kenechukwu Mark
  email: kenechukwubanego@gmail.com





